PORT=5000
SPOTIFY_CLIENT_ID=your_spotify_client_id
SPOTIFY_CLIENT_SECRET=your_spotify_client_secret
SPOTIFY_REDIRECT_URI=https://spotik.onrender.com/api/auth/callback
FRONTEND_URL=https://spotik-1.onrender.com
SESSION_SECRET=mysecret987
REACT_APP_API_URL=https://YOUR_BACKEND_URL

services:
  - type: web
    name: spotik-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://spotik.onrender.com 